### ISSUE TITLE
GET request with parameters issue

### ISSUE THREAD

**Issue by ASH19992** [cpageler93/SwiftyHawk#1]
Hi there, 
I am using your library and it works fine so far but for some reason when I try to send "GET" request with parameters the header result doesn't match the backend value. For example www.example.com/type?=SwiftyHawk
Any help :) !

**Comment by cpageler93** [comment]
Hi @ASH19992,

i think there was a little bug when using query parameters, i made a fix which should resolve that issue.
Are you able to test the library using the branch `fix/query-parameter-issue-#1` to see if everything works for your case?

Thanks,
Christoph

**Comment by cpageler93** [comment]
Hi @ASH19992,

i merged everything, so you can use the new tag 0.1.4 instead of the branch.

Thanks!
